services:
  apache:
    image: ghcr.io/fab-infra/apache:2.4-opensuse15
    ports:
      - '127.0.0.10:80:80'
    volumes:
      - '.:/srv/www/sd/static/htdocs'
    environment:
      - HOME=/srv/www
      - SERVER_NAME=static.dev.jediholo.net
      - SERVER_ENV=development
      - DEFAULT_DOCROOT=/srv/www/sd/static/htdocs
      - LISTEN_HTTP_PORT=80
